# Generated by Django 4.2.5 on 2023-09-04 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Subject',
            new_name='subject',
        ),
    ]
